# --- CORE SETTINGS ---
listen=YES
listen_ipv6=NO
anonymous_enable=YES

# CRITICAL: Point to the read-only folder we created in Dockerfile
anon_root=/srv/ftp

# --- DOCKER/WSL STABILITY FIXES ---
seccomp_sandbox=NO
background=NO
secure_chroot_dir=/var/run/vsftpd/empty

# --- PASSIVE MODE ---
pasv_enable=YES
pasv_min_port=30000
pasv_max_port=30010
# For local testing, this is usually safest
pasv_address=127.0.0.1



# Logging
xferlog_enable=YES
xferlog_file=/var/log/vsftpd.log